version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27018:27018
  api:
    build:
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27018
  client:
    build:
      context: ./client
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - 8080:80
